FROM ruby:2.5-alpine3.7

RUN apk add --update alpine-sdk nodejs

RUN gem install rails --pre --no-ri --no-rdoc

WORKDIR /app

# ADD Gemfile $WORKDIR/Gemfile
# ADD Gemfile.lock $WORKDIR/Gemfile.lock
#
# RUN bundle install
#
# ADD . $WORKDIR
#
# # CMD rm tmp/pids/server.pid 2> /dev/null; bundle exec rails s -p 3000 -b 0.0.0.0
